[package]
name = "nanoshell"
version = "0.1.0"
authors = ["Matej Knopp <matej.knopp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.119", features = ["derive"] }
serde_json = "1.0"
serde_bytes = "0.11.5"
log = "0.4.13"
velcro = "0.5.3"
lazy_static = "1.4.0"
diff = "0.1.12"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24"
core-foundation = "0.9"
core-graphics = "0.22"
dispatch = "0.2.0"
objc = "0.2.7"
block = "0.1.6"

[target.'cfg(target_os = "windows")'.dependencies]
windows = "0.3.1"
utf16_lit = "2.0.1"
const-cstr = "0.3.0"
widestring = "0.2.2"
byte-slice-cast = "1.0.0"
detour = {version = "0.7.1", default-features = false }

[target.'cfg(target_os = "windows")'.build-dependencies]
windows = "0.3.1"
